[package]
name = "acrusto"
version = "0.1.0"
authors = ["shybyte <ein@volloeko.de>"]

[dependencies]
reqwest = "0.8.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0"

[profile.release]
#opt-level = "s"
lto = true