[package]
name = "acrusto"
version = "0.1.0"
authors = ["shybyte <ein@volloeko.de>"]
edition = "2018"

[dependencies]
reqwest = "0.8.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0"
clap = "2.29.2"
hyper = "0.11.x"

[profile.release]
opt-level = "z"
lto = true